modLoader = "javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="rubber_tires"
version="1.0.0"
displayName="Sussy Skibidi Tires"
logoFile="logo.png"
authors=["bodergob373"]
description='''
skibbiti dop dop dop yes yes
'''

[[dependencies.rubber_tires]]
modId = "forge"
mandatory = true
versionRange="[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rubber_tires]]
modId = "minecraft"
mandatory = true
versionRange="[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.rubber_tires]]
modId = "create"
mandatory = true
versionRange = "0.5.1.e"
ordering = "AFTER"
side = "BOTH"